### ISSUE TITLE
Make case insensitive the default

### ISSUE THREAD

**Issue by iqbal-lab** [mbhall88/psdm#1]
We've been freaking out about some enormous SNP distances in covid genomes, but it turned out we hadn't used the ignore-case option. Up to you, but it might be a good idea to default this to yes?

**Comment by mbhall88** [comment]
Fair. snp-dists has the same default behaviour (it uppercases everything by default), so makes sense.

Didn't realise you had been using it for the covid stuff. Glad some people are using it and stress testing it. Let me know if there are any other things you'd like.

**Comment by mbhall88** [comment]
Closed in https://github.com/mbhall88/psdm/releases/tag/0.2.0
